# Telco Customer Churn  
## Data Preprocessing & Database Loading Pipeline

This notebook performs data cleaning, validation,
and loads the processed dataset into SQL Server.

importing libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

## 1. Data Loading
Load the raw dataset from Excel file.

In [3]:
df=pd.read_excel('Telco_customer_churn.xlsx')

In [4]:
df

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

## 2. Initial Data Exploration
Quick structural inspection of dataset
(shape, types, missing values, uniqueness, summary stats).

In [5]:
def explore_data(df):
    print("="*50)
    print("📌 DATA SHAPE")
    print("="*50)
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")
    
    print("\n" + "="*50)
    print("📌 DATA TYPES")
    print("="*50)
    print(df.dtypes)
    
    print("\n" + "="*50)
    print("📌 MISSING VALUES")
    print("="*50)
    print(df.isnull().sum())
    
    print("\n" + "="*50)
    print("📌 UNIQUE VALUES COUNT")
    print("="*50)
    print(df.nunique())
    
    print("\n" + "="*50)
    print("📌 NUMERICAL SUMMARY")
    print("="*50)
    print(df.describe())

In [6]:
explore_data(df)

==================================================
📌 DATA SHAPE
==================================================
Rows: 7043
Columns: 33

==================================================
📌 DATA TYPES
==================================================
CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

==================================================
📌 MISSING VALUES
==================================================
CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

==================================================
📌 UNIQUE VALUES COUNT
==================================================
CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6530
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

==================================================
📌 NUMERICAL SUMMARY
==================================================
        Count      Zip Code     Latitude    Longitude  Tenure Months  \
count  7043.0   7043.000000  7043.000000  7043.000000    7043.000000
mean      1.0  93521.964646    36.282441  -119.798880      32.371149
std       0.0   1865.794555     2.455723     2.157889      24.559481
min       1.0  90001.000000    32.555828  -124.301372       0.000000
25%       1.0  92102.000000    34.030915  -121.815412       9.000000
50%       1.0  93552.000000    36.391777  -119.730885      29.000000
75%       1.0  95351.000000    38.224869  -118.043237      55.000000
max       1.0  96161.000000    41.962127  -114.192901      72.000000

       Monthly Charges  Churn Value  Churn Score         CLTV
count      7043.000000  7043.000000  7043.000000  7043.000000
mean         64.761692     0.265370    58.699418  4400.295755
std          30.090047     0.441561    21.525131  1183.057152
min          18.250000     0.000000     5.000000  2003.000000
25%          35.500000     0.000000    40.000000  3469.000000
50%          70.350000     0.000000    61.000000  4527.000000
75%          89.850000     1.000000    75.000000  5380.500000
max         118.750000     1.000000   100.000000  6500.000000

## 3. Data Cleaning
Removing irrelevant columns and correcting data types.

In [7]:
df.drop(columns=[
    'Count','Zip Code','Longitude','Latitude','Lat Long',
    'Churn Value','Country','State'
], inplace=True)

### Type Correction
Convert `Total Charges` to numeric to ensure proper aggregation and storage.

In [8]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

In [9]:
explore_data(df)

==================================================
📌 DATA SHAPE
==================================================
Rows: 7043
Columns: 25

==================================================
📌 DATA TYPES
==================================================
CustomerID            object
City                  object
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Label           object
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

==================================================
📌 MISSING VALUES
==================================================
CustomerID              0
City                    0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges          11
Churn Label             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

==================================================
📌 UNIQUE VALUES COUNT
==================================================
CustomerID           7043
City                 1129
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6529
Churn Label             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

==================================================
📌 NUMERICAL SUMMARY
==================================================
       Tenure Months  Monthly Charges  Total Charges  Churn Score         CLTV
count    7043.000000      7043.000000    7032.000000  7043.000000  7043.000000
mean       32.371149        64.761692    2283.312848    58.699418  4400.295755
std        24.559481        30.090047    2266.766847    21.525131  1183.057152
min         0.000000        18.250000      18.800000     5.000000  2003.000000
25%         9.000000        35.500000     401.450000    40.000000  3469.000000
50%        29.000000        70.350000    1397.475000    61.000000  4527.000000
75%        55.000000        89.850000    3794.737500    75.000000  5380.500000
max        72.000000       118.750000    8684.800000   100.000000  6500.000000

### Handling Missing Values
Remove records where `Total Charges` is missing.

In [10]:
df = df.dropna(subset=['Total Charges'])

In [11]:
explore_data(df)

==================================================
📌 DATA SHAPE
==================================================
Rows: 7032
Columns: 25

==================================================
📌 DATA TYPES
==================================================
CustomerID            object
City                  object
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Label           object
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

==================================================
📌 MISSING VALUES
==================================================
CustomerID              0
City                    0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Score             0
CLTV                    0
Churn Reason         5163
dtype: int64

==================================================
📌 UNIQUE VALUES COUNT
==================================================
CustomerID           7032
City                 1129
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          72
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1584
Total Charges        6529
Churn Label             2
Churn Score            85
CLTV                 3435
Churn Reason           20
dtype: int64

==================================================
📌 NUMERICAL SUMMARY
==================================================
       Tenure Months  Monthly Charges  Total Charges  Churn Score         CLTV
count    7032.000000      7032.000000    7032.000000  7032.000000  7032.000000
mean       32.421786        64.798208    2283.312848    58.715301  4401.445108
std        24.545260        30.085974    2266.766847    21.531321  1182.414266
min         1.000000        18.250000      18.800000     5.000000  2003.000000
25%         9.000000        35.587500     401.450000    40.000000  3469.750000
50%        29.000000        70.350000    1397.475000    61.000000  4527.500000
75%        55.000000        89.862500    3794.737500    75.000000  5381.000000
max        72.000000       118.750000    8684.800000   100.000000  6500.000000

## 4. Database Connection & Data Insertion
Establish SQL Server connection and load cleaned data.

In [12]:
server = 'localhost'   
database = 'churn_analysis_project'

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

df.to_sql("telco_churn_data", engine, if_exists="replace", index=False)

C:\Users\moham\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\sql.py:1636: SAWarning: Unrecognized server version info '17.0.1050.2'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

60

In [13]:
df

,CustomerID,City,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,...,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,Los Angeles,Male,No,No,No,2,Yes,No,DSL,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,86,3239,Competitor made better offer
1,9237-HQITU,Los Angeles,Female,No,No,Yes,2,Yes,No,Fiber optic,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,67,2701,Moved
2,9305-CDSKC,Los Angeles,Female,No,No,Yes,8,Yes,Yes,Fiber optic,...,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,86,5372,Moved
3,7892-POOKP,Los Angeles,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,...,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,84,5003,Moved
4,0280-XJGEX,Los Angeles,Male,No,No,Yes,49,Yes,Yes,Fiber optic,...,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,Landers,Female,No,No,No,72,Yes,No,No,...,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,No,45,5306,NaN
7039,6840-RESVB,Adelanto,Male,No,Yes,Yes,24,Yes,Yes,DSL,...,Yes,One year,Yes,Mailed check,84.80,1990.50,No,59,2140,NaN
7040,2234-XADUH,Amboy,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No,71,5560,NaN
7041,4801-JZAZL,Angelus Oaks,Female,No,Yes,Yes,11,No,No phone service,DSL,...,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,59,2793,NaN
7042,3186-AJIEK,Apple Valley,Male,No,No,No,66,Yes,No,Fiber optic,...,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No,38,5097,NaN